<?php

namespace symply;

/**
 * @internal
 * Constants for all properties available in symply.yml.
 * This is generated by build/generate-symply-yml-property-consts.php.
 * Do not edit this file manually.
 */
class YmlSymplyProperties
{
	private function __construct(){
		//NOOP
	}

	public const PERSONA_SKIN = 'persona-skin';
}