name: "📦 API change request"
description: "Suggest a change, addition, or removal to the plugin API"
title: "[API]: "
labels: ["Type: API", "Status: Unconfirmed"]

body:
  - type: markdown
    attributes:
      value: |
        **Thank you :heart: for taking the time to fill in this API change request report!**
        Please check if there is an [existing issue](https://github.com/SymplyX/Symply/pulls) for your proposed change.
        
        We are also happy to accept contributions from our users. For more details, refer [here](https://github.com/SymplyX/Symply/blob/stable/CONTRIBUTING.md).

  - type: textarea
    attributes:
      label: Description
      description: |
        Provide a clear, concise description of the addition or modification you are proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Justification
      description: |
        Describe the solution you'd like. Provide a clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Change List
      description: |
        List all changes in a clear format.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Prior Research
      description: "Have you performed prior research to avoid duplicates?"
      options:
        - label: "I have performed prior research"
          required: true
