blank_issues_enabled: false
contact_links:
  - name: Help & support on Discord
    url: https://discord.gg/V4mNumXyvd
    about: Are you interested in the project or just looking for help ? Join the discord !
